Initial commit for MOZ-SMC
HCM-MOZ-IMPEL/health-campaign-field-worker-app-impel pull request #114
Opened 2024-10-14 10:22 UTC by amitverma-egov

Initial commit for MOZ-SMC

2024-10-15 05:37 UTC, vishal-egov requested changes

2024-10-15 05:37 UTC, vishal-egov commented on apps/health_campaign_field_worker_app/lib/blocs/blocs-smc/closed/closed_household.dart
> +      // print("Task - ${task}");
remove the comment

2024-10-15 05:37 UTC, vishal-egov commented on apps/health_campaign_field_worker_app/lib/pages/pages-SMC/beneficiary/widgets/consent_household_acknowledgement.dart
> +// import '../../../widgets/localized.dart';
remove the comments

2024-10-15 05:37 UTC, vishal-egov commented on apps/health_campaign_field_worker_app/lib/pages/pages-SMC/beneficiary/custom_beneficiary_details_smc.dart
> +                                    //         ),
rmove the comments

2024-10-21 04:56 UTC, amitverma-egov commented on apps/health_campaign_field_worker_app/lib/blocs/blocs-smc/closed/closed_household.dart
> +      // print("Task - ${task}");
removed

2024-11-18 11:55 UTC, vishal-egov approved these changes

2024-11-18 11:55 UTC, merged